concurrent = 1
check_interval = 0
shutdown_timeout = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "runner"
  url = "http://gitlab.local:8929"
  id = 1
  token = "glrt-VxeHdUlIbU1I5mb61qdbTm86MQpwOjEKdDozCnU6MQ8.01.170veui80"
  token_obtained_at = 2025-08-23T11:35:13Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "shell"
  [runners.cache]
    MaxUploadedArchiveSize = 0
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]
